name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get install cmake

    - name: build
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build build -j $(nproc)

    - name: Upload
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: devilutionx-gamelist-Linux-x64
        path: build/devilutionx-gamelist
