name: Python tool distributions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Build distributions
      run: pipx run build

    - name: Upload
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: discord_bot
        path: dist/*
