name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: build
      run: |
        cmake -S. -Bbuild
        cmake --build build -j $(nproc)

    - name: Upload
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: devilutionx-gamelist-Windows-x64
        path: build\Debug\devilutionx-gamelist.exe
